// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
import 'dart:core';
import 'package:hive/hive.dart' as prefix5;
import 'package:json_annotation/src/json_serializable.dart' as prefix7;
import 'package:promise/models/hive_type_model.const.dart' as prefix6;
import 'package:promise/models/memory/memory.dart' as prefix1;
import 'package:promise/models/person/person.dart' as prefix2;
import 'package:promise/models/promise/promise.dart' as prefix3;
import 'package:promise/models/system-versions/system-version.model.dart'
    as prefix4;
import 'package:promise/util/reflectable.hive.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import

import 'package:reflectable/mirrors.dart' as m;
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.HiveTypeReflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'Memory',
            r'.Memory',
            134217735,
            0,
            const prefix0.HiveTypeReflector(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => ({id, description}) =>
                  b ? prefix1.Memory(description: description, id: id) : null,
              r'fromJson': (bool b) =>
                  (json) => b ? prefix1.Memory.fromJson(json) : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              const prefix5.HiveType(typeId: prefix6.MemoryHiveType),
              prefix0.hiveTypeReflector
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'capabilities': 0,
              r'canReflect': 1,
              r'reflect': 1,
              r'canReflectType': 1,
              r'reflectType': 1,
              r'findLibrary': 1,
              r'libraries': 0,
              r'annotatedClasses': 0,
              r'id': 0,
              r'id=': 1,
              r'userId': 0,
              r'userId=': 1,
              r'createdAt': 0,
              r'createdAt=': 1,
              r'updatedAt': 0,
              r'updatedAt=': 1,
              r'fromJsonMethod': 0,
              r'description': 0,
              r'description=': 1
            }),
        r.NonGenericClassMirrorImpl(
            r'Person',
            r'.Person',
            134217735,
            1,
            const prefix0.HiveTypeReflector(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => ({id, nickname}) =>
                  b ? prefix2.Person(id: id, nickname: nickname) : null,
              r'fromJson': (bool b) =>
                  (json) => b ? prefix2.Person.fromJson(json) : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              const prefix5.HiveType(typeId: prefix6.PersonHiveType),
              const prefix7.JsonSerializable(),
              prefix0.hiveTypeReflector
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'capabilities': 0,
              r'canReflect': 1,
              r'reflect': 1,
              r'canReflectType': 1,
              r'reflectType': 1,
              r'findLibrary': 1,
              r'libraries': 0,
              r'annotatedClasses': 0,
              r'id': 0,
              r'id=': 1,
              r'userId': 0,
              r'userId=': 1,
              r'createdAt': 0,
              r'createdAt=': 1,
              r'updatedAt': 0,
              r'updatedAt=': 1,
              r'fromJsonMethod': 0,
              r'nickname': 0
            }),
        r.NonGenericClassMirrorImpl(
            r'Promise',
            r'.Promise',
            134217735,
            2,
            const prefix0.HiveTypeReflector(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => ({id, content, to = null, dueDate = null}) => b
                  ? prefix3.Promise(
                      dueDate: dueDate, to: to, content: content, id: id)
                  : null,
              r'fromJson': (bool b) =>
                  (json) => b ? prefix3.Promise.fromJson(json) : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              const prefix5.HiveType(typeId: prefix6.PromiseHiveType),
              const prefix7.JsonSerializable(),
              prefix0.hiveTypeReflector
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'capabilities': 0,
              r'canReflect': 1,
              r'reflect': 1,
              r'canReflectType': 1,
              r'reflectType': 1,
              r'findLibrary': 1,
              r'libraries': 0,
              r'annotatedClasses': 0,
              r'id': 0,
              r'id=': 1,
              r'userId': 0,
              r'userId=': 1,
              r'createdAt': 0,
              r'createdAt=': 1,
              r'updatedAt': 0,
              r'updatedAt=': 1,
              r'toJson': 0,
              r'fromJsonMethod': 0,
              r'content': 0,
              r'content=': 1,
              r'dueDate': 0,
              r'dueDate=': 1,
              r'to': 0,
              r'to=': 1
            }),
        r.NonGenericClassMirrorImpl(
            r'SystemVersion',
            r'.SystemVersion',
            134217735,
            3,
            const prefix0.HiveTypeReflector(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => ({id, userId, versions}) => b
                  ? prefix4.SystemVersion(
                      id: id, userId: userId, versions: versions)
                  : null,
              r'fromJson': (bool b) =>
                  (json) => b ? prefix4.SystemVersion.fromJson(json) : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              const prefix5.HiveType(typeId: prefix6.SystemVersionHypeType),
              prefix0.hiveTypeReflector
            ],
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'capabilities': 0,
              r'canReflect': 1,
              r'reflect': 1,
              r'canReflectType': 1,
              r'reflectType': 1,
              r'findLibrary': 1,
              r'libraries': 0,
              r'annotatedClasses': 0,
              r'id': 0,
              r'id=': 1,
              r'userId': 0,
              r'userId=': 1,
              r'versions': 0,
              r'versions=': 1
            })
      ],
      null,
      null,
      <Type>[
        prefix1.Memory,
        prefix2.Person,
        prefix3.Promise,
        prefix4.SystemVersion
      ],
      4,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'capabilities': (dynamic instance) => instance.capabilities,
        r'canReflect': (dynamic instance) => instance.canReflect,
        r'reflect': (dynamic instance) => instance.reflect,
        r'canReflectType': (dynamic instance) => instance.canReflectType,
        r'reflectType': (dynamic instance) => instance.reflectType,
        r'findLibrary': (dynamic instance) => instance.findLibrary,
        r'libraries': (dynamic instance) => instance.libraries,
        r'annotatedClasses': (dynamic instance) => instance.annotatedClasses,
        r'id': (dynamic instance) => instance.id,
        r'userId': (dynamic instance) => instance.userId,
        r'createdAt': (dynamic instance) => instance.createdAt,
        r'updatedAt': (dynamic instance) => instance.updatedAt,
        r'fromJsonMethod': (dynamic instance) => instance.fromJsonMethod,
        r'description': (dynamic instance) => instance.description,
        r'nickname': (dynamic instance) => instance.nickname,
        r'toJson': (dynamic instance) => instance.toJson,
        r'content': (dynamic instance) => instance.content,
        r'dueDate': (dynamic instance) => instance.dueDate,
        r'to': (dynamic instance) => instance.to,
        r'versions': (dynamic instance) => instance.versions
      },
      {
        r'id=': (dynamic instance, value) => instance.id = value,
        r'userId=': (dynamic instance, value) => instance.userId = value,
        r'createdAt=': (dynamic instance, value) => instance.createdAt = value,
        r'updatedAt=': (dynamic instance, value) => instance.updatedAt = value,
        r'description=': (dynamic instance, value) =>
            instance.description = value,
        r'content=': (dynamic instance, value) => instance.content = value,
        r'dueDate=': (dynamic instance, value) => instance.dueDate = value,
        r'to=': (dynamic instance, value) => instance.to = value,
        r'versions=': (dynamic instance, value) => instance.versions = value
      },
      null,
      [
        const [0, 0, null],
        const [1, 0, null],
        const [
          0,
          0,
          const [#id, #description]
        ],
        const [
          0,
          0,
          const [#id, #nickname]
        ],
        const [
          0,
          0,
          const [#id, #content, #to, #dueDate]
        ],
        const [
          0,
          0,
          const [#id, #userId, #versions]
        ]
      ])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
